extension/learn

app/views/events/_main_event.html.erb
added similar events to event view
=> added similar events to event view

app/controllers/data_controller.rb, app/helpers/application_helper.rb, app/models/event.rb, app/views/data/_date_form.html.erb, app/views/data/events.html.erb, app/views/data/events_csvlist.html.erb, config/routes.rb
Replaced tag text field with token input
=> Add tag select to metrics

app/models/comment.rb, app/models/event.rb, app/models/event_connection.rb, app/views/data/events.html.erb, db/migrate/20141222193525_add_counts_to_events.rb
=> Fix event counts

app/models/event_connection.rb
fixed update counts and removed event.save in connectionType
=> fixed update counts and removed event.save in connectionType

app/views/data/events_csvlist.html.erb
removed raters and added commas to tags in event csv download
=> removed raters and added commas to tags in event csv download

app/controllers/data_controller.rb, app/models/comment.rb, app/models/event.rb, app/views/data/events.html.erb
Use count columns in sorting data on data/events page
=> Use column counts

app/controllers/data_controller.rb
Add materials and evaluation to csv
=> Add materials and eval to csv

app/controllers/events_controller.rb
My bad. Must have been a typo on one of my commits.
=> fix tags method name

db/migrate/20150224184639_add_default_values_to_versions.rb, db/schema.rb
add default values to whodunnit and ipaddress, and set existing null values to user 1 and ipaddy localhost
=> add default values to whodunnit and ipaddress

app/controllers/learners_controller.rb, app/views/learners/learning_history.html.erb, config/routes.rb
remove Rated history from learner view
=> remove Rated history from learner view

app/helpers/application_helper.rb
replaced string with contant from settings.yml
=> replaced string with contant from settings.yml

app/views/events/_main_event.html.erb, app/views/home/index.html.erb
modified time_zone_select to get/display system time if default is nil
=> modified time_zone_select to get/display system time if default is nil

app/assets/stylesheets/all/_bootstrap_overrides.css.scss, app/assets/stylesheets/all/events.css.scss, app/assets/stylesheets/all/global.css.scss, app/assets/stylesheets/all/responsive.css.scss, app/views/events/_main_event.html.erb, app/views/events/_online_event_form.html.erb, app/views/learners/sessions/new.html.erb
* Modify sign-in screen so it displays well on mobile. Adjust the desktop view to better take advantage of a wider screen.
* tweak misc typography for better sizing in mobile
* be consistent with location labels on show event view
=> Mobile tweaks

app/models/notification.rb
Turn email and sms off for deleted events
=> Turn email and sms off for deleted events

app/assets/javascripts/events.js.coffee, app/controllers/events_controller.rb, app/models/event.rb, app/views/event_mailer/event_deleted.html.erb, app/views/events/delete_event.html.erb, app/views/events/edit.html.erb, app/views/events/show.html.erb, config/routes.rb, db/migrate/20150715135832_add_reason_to_deleted_events.rb, db/schema.rb
=> Add reason to deleted events

app/controllers/learners_controller.rb, app/views/events/_main_event.html.erb, app/views/events/_registration_modal.html.erb
=> Add modal to registration

Gemfile, Gemfile.lock, app/assets/javascripts/events.js.coffee, app/controllers/learners_controller.rb, app/models/event_registration.rb, app/views/events/_main_event.html.erb
Refactor event registration validation. Removed JS validation and moved it to mode/controller.
=> Refactor registration validation

app/assets/javascripts/events.js.coffee, app/assets/stylesheets/all/events.css.scss
- handle text input height smarter. much, much smarter
- Disablethe description field when registration is unchecked
=> Form css fix

app/views/events/diff_with_previous.html.erb
=> Wordsmithing

app/assets/stylesheets/all/global.css.scss, app/views/events/show.html.erb
Make the green circle play icon beside "Watch recording" clickable, and add attractive hover state
=> All the styles and links!
